-- Tablas

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    NAME1 VARCHAR(255) NOT NULL,
    SURNAME1 VARCHAR(255) NOT NULL,
    VISIT_DATE DATE NULL,
    OPTIONS VARCHAR(10) NULL
);

DROP TABLE IF EXISTS RESPONSE;
CREATE TABLE RESPONSE (
    OPTIONS VARCHAR(10) PRIMARY KEY NOT NULL,
    ANSWER INTEGER NOT NULL
);

DROP TABLE IF EXISTS SHOP;
CREATE TABLE SHOP (
    ID INTEGER PRIMARY KEY NOT NULL,
    ITEM VARCHAR(255) NOT NULL,
    PRICE NUMERIC NOT NULL,
    QUANTITY INTEGER NOT NULL,
    SOLD BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS PURCHASE;
CREATE TABLE PURCHASE (
    ID INTEGER NOT NULL,
    U_NAME1 VARCHAR(255) NOT NULL,
    U_SURNAME1 VARCHAR(255) NOT NULL
);